### ISSUE TITLE
Initializing a DWCj-Control as a field (class variable) is not working properly

### ISSUE THREAD

**Issue by Oskan1** [DwcJava/engine#31] opened 2022-12-05 08:17 UTC
I need to initialize a DWCj-Control inside my run() function in order to work with it. 

If I initialize it as a field, then adding it to the AppPanel won't work (but no error will be thrown, so user cannot understand what is going on) (1)

If I use the (1) and also write an Event Method e.g. (onClick, onChange - ButtonPushEvent, etc.) then I get a "cannot launch app" error.

```java
package dwcjsample;

import org.dwcj.App;
import org.dwcj.controls.Button;
import org.dwcj.events.ButtonPushEvent;
import org.dwcj.exceptions.DwcAppInitializeException;
import org.dwcj.panels.AppPanel;

public class ControlFieldInitializeErrorSample extends App {

    private Button button = new Button("hey");

    @Override
    public void run() throws DwcAppInitializeException {
        AppPanel appPanel = new AppPanel();
        appPanel.add(button);

        button.onClick(this::onButtonClick);
        new SampleAppPanel();
    }
    private void onButtonClick(ButtonPushEvent buttonPushEvent){
        button.setText("clicked");
    }
}
```

the code above doesn't work. But if I use the one below.

```java
package dwcjsample;

import org.dwcj.controls.Button;
import org.dwcj.exceptions.DwcAppInitializeException;
import org.dwcj.panels.AppPanel;

public class StephanMethod extends AppPanel{

    private Button myButton = new Button("myTdddext");

    public StephanMethod() throws DwcAppInitializeException {
        super();
        add(myButton);
    }
}
```

then add it on the following class:

```java
package dwcjsample;

import org.dwcj.App;
import org.dwcj.exceptions.DwcAppInitializeException;

public class MyClass extends App {
    @Override
    public void run() throws DwcAppInitializeException {
        new StephanMethod();
    }
}
```

then everything compiles as it suppose to be.

**Comment by hyyan** [comment] 2023-12-16 00:04
Duplicate of https://github.com/DwcJava/engine/issues/369

**Closed by hyyan** 2023-12-16 00:04 UTC
